# -*- coding: utf-8 -*-
"""Airline Review Sentiment Analysis NLP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kiVbGM6HISvixukLC1cF_MGDMnrbQp-X

# Fine-tuning a model on a text classification task

## Loading the dataset
"""

from datasets import load_dataset

dataset = load_dataset("TCRG/airline_reviews")

# Split train into train + validation
split_dataset = dataset["train"].train_test_split(test_size=0.2, seed=42)

dataset = {
    "train": split_dataset["train"],
    "validation": split_dataset["test"],
    "test": dataset["test"]
}

print(dataset["train"])
print(dataset["validation"])
print(dataset["test"])

import datasets
import random
import pandas as pd
from IPython.display import display, HTML

def show_random_elements(dataset, num_examples=10):
    assert num_examples <= len(dataset), "Can't pick more elements than there are in the dataset."
    picks = []
    for _ in range(num_examples):
        pick = random.randint(0, len(dataset)-1)
        while pick in picks:
            pick = random.randint(0, len(dataset)-1)
        picks.append(pick)

    df = pd.DataFrame(dataset[picks])
    for column, typ in dataset.features.items():
        if isinstance(typ, datasets.ClassLabel):
            df[column] = df[column].transform(lambda i: typ.names[i])
    display(HTML(df.to_html()))

show_random_elements(dataset["train"])

"""## Data Understanding
Inital EDA
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

reviews_train = dataset["train"].to_pandas() # 6380
reviews_test = dataset["test"].to_pandas() # 709

# Combine train and test for EDA
reviews = pd.concat([reviews_train, reviews_test]) # 7089

print("\nAll reviews count:")
print(reviews.count())

# Check for NAs or empty strings
print("\nNA counts:")
print(reviews.isna().sum())

print(reviews["label"].value_counts().sort_index())

# Visualize
sns.countplot(x=reviews["label"], order=[0, 1, 2])
plt.xticks([0, 1, 2], ["Negative", "Neutral", "Positive"])
plt.xlabel("Sentiment")
plt.ylabel("Count")
plt.title("Class Distribution of Airline Review Sentiment")
plt.show()

reviews["word_count"] = reviews["text"].str.split().str.len()

print("\nWord count summary:")
print("Min:", reviews["word_count"].min())
print("Max:", reviews["word_count"].max())
print("Mean:", reviews["word_count"].mean())

sns.histplot(reviews["word_count"])
plt.xlabel("Word count")
plt.ylabel("Number of reviews")
plt.title("Distribution of Review Lengths")
plt.show()

from wordcloud import WordCloud
import matplotlib.pyplot as plt
# word cloud for reviews classified as positive
# word cloud for reviews classified as neutral
# word cloud for reviews classified as negative

from wordcloud import WordCloud, STOPWORDS

custom_stopwords = set(STOPWORDS)

custom_stopwords.update([
    "and", "to", "the", "of", "in", "for", "on", "with", "now",
    "flight", "airline", "airlines", "t", "co"
])

def plot_wordcloud(text, title):
    wc = WordCloud(
        width=800,
        height=400,
        background_color='white',
        stopwords=custom_stopwords
    ).generate(text)

    plt.figure(figsize=(10, 5))
    plt.imshow(wc, interpolation='bilinear')
    plt.title(title)
    plt.axis('off')
    plt.show()

# Negative (0)
negative_text = " ".join(reviews[reviews["label"] == 0]["text"])
plot_wordcloud(negative_text, "Negative Reviews Word Cloud")

# Neutral (1)
neutral_text = " ".join(reviews[reviews["label"] == 1]["text"])
plot_wordcloud(neutral_text, "Neutral Reviews Word Cloud")

# Positive (2)
positive_text = " ".join(reviews[reviews["label"] == 2]["text"])
plot_wordcloud(positive_text, "Positive Reviews Word Cloud")

"""## Preprocessing the data

Preprocess text with transformers `Tokenizer`. Change commented out lines for DistilBERT, BERT, and RoBERTa models.
"""

from transformers import AutoTokenizer

# Uncomment desired model
model_checkpoint = "distilbert-base-uncased"
# model_checkpoint = "bert-base-uncased"
# model_checkpoint = "roberta-base"

tokenizer = AutoTokenizer.from_pretrained(model_checkpoint, use_fast=True)

def preprocess_function(examples):
    return tokenizer(examples["text"], truncation=True)

encoded_dataset = {}
for split in dataset:
    encoded_dataset[split] = dataset[split].map(preprocess_function, batched=True)

"""## Fine-tuning the model

Load the pretrained model and fine-tune it, use the `AutoModelForSequenceClassification` class. Specify is the # of labels as 3: positive, negative, neutral.
"""

from transformers import AutoModelForSequenceClassification

num_labels = 3

model = AutoModelForSequenceClassification.from_pretrained(
    model_checkpoint,
    num_labels=num_labels
)

"""Setting up metrics

"""

import numpy as np
from sklearn.metrics import accuracy_score, f1_score

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return {
        "accuracy": accuracy_score(labels, predictions),
        "macro_f1": f1_score(labels, predictions, average="macro")
    }

from transformers import TrainingArguments

batch_size = 16

training_args = TrainingArguments(

    # Uncomment desired model
    output_dir="./distilbert-airline-sentiment",
    #output_dir="./bert-airline-sentiment",
    #output_dir="./roberta-airline-sentiment",

    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=batch_size,
    per_device_eval_batch_size=batch_size,
    num_train_epochs=3,
    weight_decay=0.01,
    load_best_model_at_end=True,
    metric_for_best_model="macro_f1",
    greater_is_better=True,
    push_to_hub=False
)

from transformers import Trainer, DataCollatorWithPadding

data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=encoded_dataset["train"],
    eval_dataset=encoded_dataset["validation"],
    data_collator=data_collator,
    compute_metrics=compute_metrics
)

trainer.train()

trainer.evaluate()

test_results = trainer.predict(encoded_dataset["test"])
test_preds = np.argmax(test_results.predictions, axis=-1)

from sklearn.metrics import classification_report, confusion_matrix

print(classification_report(encoded_dataset["test"]["label"], test_preds))
print(confusion_matrix(encoded_dataset["test"]["label"], test_preds))

import matplotlib.pyplot as plt
import numpy as np

# Data
models = ["DistilBERT", "BERT", "RoBERTa"]
val_accuracy = [0.8386, 0.8448, 0.8519]
val_macro_f1 = [0.8384, 0.8447, 0.8522]

x = np.arange(len(models))
width = 0.35

plt.figure(figsize=(8, 5))
bars1 = plt.bar(x - width/2, val_accuracy, width, label="Validation Accuracy")
bars2 = plt.bar(x + width/2, val_macro_f1, width, label="Validation Macro F1")

plt.xticks(x, models)
plt.ylim(0.80, 0.87)
plt.ylabel("Score")
plt.xlabel("Model")
plt.title("Validation Accuracy and Macro F1 by Model")
plt.legend()

# Add value labels above bars
for bar in bars1:
    height = bar.get_height()
    plt.text(
        bar.get_x() + bar.get_width()/2,
        height + 0.001,
        f"{height:.4f}",
        ha="center",
        va="bottom",
        fontsize=9
    )

for bar in bars2:
    height = bar.get_height()
    plt.text(
        bar.get_x() + bar.get_width()/2,
        height + 0.001,
        f"{height:.4f}",
        ha="center",
        va="bottom",
        fontsize=9
    )

plt.tight_layout()
plt.savefig("model_comparison.png", dpi=300, bbox_inches="tight")
plt.show()

import matplotlib.pyplot as plt
import numpy as np

# RoBERTa confusion matrix
cm = np.array([
    [197, 27, 12],
    [24, 187, 25],
    [7, 31, 199]
])

class_names = ["Negative", "Neutral", "Positive"]

plt.figure(figsize=(6, 5))
plt.imshow(cm, interpolation="nearest")
plt.title("RoBERTa Confusion Matrix")
plt.colorbar()

tick_marks = np.arange(len(class_names))
plt.xticks(tick_marks, class_names)
plt.yticks(tick_marks, class_names)
plt.xlabel("Predicted Label")
plt.ylabel("True Label")

# Add counts inside cells
threshold = cm.max() / 2
for i in range(cm.shape[0]):
    for j in range(cm.shape[1]):
        plt.text(
            j, i, str(cm[i, j]),
            ha="center",
            va="center",
            color="white" if cm[i, j] > threshold else "black",
            fontsize=11
        )

plt.tight_layout()
plt.savefig("roberta_confusion_matrix.png", dpi=300, bbox_inches="tight")
plt.show()